---
version: "3.8"

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
#      - "9088:80"
      - "9443:443"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - laravel-php
      - mysql
    networks:
      - laravel

  # mysql
  mysql:
    image: mysql:8
    container_name: laravel-mysql
    restart: unless-stopped
    tty: true

    ports:
      - "4306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=Europe/Rome
    networks:
      - laravel

  laravel-php:
    image: laravel-php
    build:
      context: ./
      dockerfile: Dockerfile-php
      args:
        - APP_ENV=${APP_ENV}
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: laravel-php
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - APP_ENV=${APP_ENV}
      - TZ=Europe/Rome
    volumes:
      - ./src:/var/www/html
    ports:
#      - "9000:9000"
      - "5173:5173"
    networks:
      - laravel

  queue:
    restart: always
    image: laravel-php
    container_name: laravel-queue
    command: php /var/www/html/artisan queue:work
    depends_on:
      - laravel-php
    volumes:
      - ./src:/var/www/html/
    networks:
      - laravel

  crontab:
    container_name: laravel-crontab
    build:
      context: ./
      dockerfile: Dockerfile-cron
      args:
        - APP_ENV=${APP_ENV}
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    restart: unless-stopped
    environment:
      - APP_ENV=${APP_ENV}
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel
